create table if not exists public.records (
  id bigint generated by default as identity primary key,
  date date not null,
  type text not null check (type in ('xixi', 'coco', 'ambos')),
  size text not null default 'M' check (size in ('RN', 'P', 'M', 'G', 'XG', 'XXG')),
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_records_date on public.records(date);
create index if not exists idx_records_type on public.records(type);
create index if not exists idx_records_size on public.records(size);
